repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: end-of-file-fixer
    - id: check-executables-have-shebangs
    - id: mixed-line-ending
      args: [--fix=lf]
    - id: no-commit-to-branch
    - id: trailing-whitespace

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.77.0
  hooks:
    - id: terraform_fmt
    - id: terraform_tflint
      args:
        - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl

files: |
    (?x)(
        ^oci-wekaopn/|
        ^oci-k8s/|
        ^tf/
    )
