name: CI

on:
  pull_request:
    branches: [main]
  
jobs:
  add-random-file:
    runs-on: ubuntu-latest

    steps:
      - name: list
        run : |
          printenv
          
      - name: Push a random file
        run: |
          echo Starting
          pwd
          ls -la
          echo
          echo Gitting
          git init
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"

          git config --global user.email "my-bot@bot.com"
          git config --global user.name "my-bot"

          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main

          git pull
          ls -la

          echo $RANDOM >> random.txt

          git add -A
          git commit -m "update"
          git push



