name: gen-draft

on:
  push:
    branches: [main]
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          minor-identifier: /feat(ure)*:/
          major-identifier: /breaking:/
      - uses: softprops/action-gh-release@v1
        with:
          draft: true
