name: TF

on: 
  pull_request:
    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: "Build Changelog"
      id: build_changelog
      uses: mikepenz/release-changelog-builder-action@v3
