name: 'CI'
on: 
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'release tag'     
        required: true


jobs:
  release:
    # if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: git log -5
      # - name: Build Changelog
      #   id: github_release
      #   uses: mikepenz/release-changelog-builder-action@v3

      - uses: azure/setup-helm@v3
        with:
          version: 3.11.1
    
      - name: custom packaging
        run: |
          rm -rf .cr-release-packages
          mkdir -p .cr-release-packages
          helm package deploy/aloha --app-version=${TAG:1} --version=${TAG:1} --destination .cr-release-packages
        env:
          TAG: ${{ github.event.inputs.releaseTag }}

      - uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          version: ${{ github.event.inputs.releaseTag }}
          skip_packaging: true

        


      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   # if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     draft: true
      #     files: test
      #     tag_name: ${{ github.event.inputs.releaseTag }}
      #     generate_release_notes: true
      #     #body: ${{steps.github_release.outputs.changelog}}
