name: CI

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - 'services/*/manifests/**'
      - 'services/*/skaffold.yaml'
      - 'services/*/Taskfile.yaml'
      - 'services/*/README.md'
      - 'flux/**'
      - 'helpers/**'
      - '*'


jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
    - uses: pre-commit/action@v3.0.0
