name: version
on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
    inputs:
      releaseTag:
        description: 'release tag'     
        required: true
      makeLatestRelease:
        type: boolean
        description: makeLatestRelease
        required: true


jobs:
  pr-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0   
      - run: |
          echo 1
          echo ${{ inputs.makeLatestRelease }}
          echo 2

      - name: Git Version
        id: version
        uses: codacy/git-version@2.7.1
        with:
          release-branch: main
          minor-identifier: /feat(ure)*:/
          major-identifier: /breaking:/

      - name: Use the version
        run: |
          echo current ${{ steps.version.outputs.version }}
          echo previous ${{ steps.version.outputs.previous-version }}

          
      - name: Update version
        run: | 
            cd charts/aloha
            
            yq -i '.version = "'$VERSION'"' Chart.yaml
            yq -i '.appVersion = "'$VERSION'"' Chart.yaml
        env:
          VERSION: ${{ steps.version.outputs.version }}


      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Release ${{ steps.version.outputs.version }}
