name: version
on:
  push:
    branches:
      - main


jobs:
  pr-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0                

      - name: Git Version
        id: auto_version
        uses: codacy/git-version@2.7.1
        with:
          minor-identifier: /feat(ure)*:/
          major-identifier: /breaking:/
